package chapter4.ClassDelegationUsingTheByKeyword1

class DelegatingCollection<T> (
    innerList: Collection<T> = ArrayList<T>()
) : Collection<T> by innerList {

}

// A better way to write code , all method implementations are gone and will all be generated by the compiler automatically...